### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by o-mercury** [Meadowcottage/Ionic-Creator#4]
Hello. I cannot use the application due to CORS errors. I get 401(Unauthorized), 403(Forbidden) errors and the message 
"XMLHttpRequest cannot load https://apps.ionic.io/api/v1/user. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://creator.ionic.io' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute"
in the console.

I've also been getting this message in all my desktop browsers (update to date Chrome and Firefox) and figured I would avoid such errors with this Electron app. Kindly point me to a solution.

**Comment by Meadowcottage** [comment]
Sadly if the error are also on your browser then they will carry over to Electron as all this app does is serve the website. And since Electron is built using Chromium, it would make sense that it would carry over.

I can only recommend contacting either the Chrome or Chromium support forums about this issue.
